### ISSUE TITLE
On installing package missing panel / not displayed. "AnamicoAlarmPanel"

### ISSUE THREAD

**Issue by superthaix** [Anamico/node-red-contrib-alarm#10]
Hi.

Upon installing the package, everything looks normal except the "AnamicoAlarmPanel" is missing and not displayed in the left hand node list. However reviewing the palette, AlarmPanel is displayed. I have installed the dependancies, async and lodash and restarted node-red but nothing changed.
Any ideas?
Thanks
Brent

![screenshot at 2019-02-06 15 16 49](https://user-images.githubusercontent.com/47402708/52378253-71ec1f80-2a24-11e9-86c7-ec014ce43569.png)
![screenshot at 2019-02-06 15 17 19](https://user-images.githubusercontent.com/47402708/52378473-fa6ac000-2a24-11e9-8521-37b5a7d26c2d.png)

**Comment by johanhansen** [comment]
AnamicoAlarmPanel is not supposed to show up as a node inte the left side node panel. You will find the settings for AnamicoAlarmPanel when editing any of the available nodes, look for the label "Panel". This is used to create one or more alarm panels for the other nodes to connect trough. I think the little grey square indicates the node type.
