### ISSUE TITLE
Bug & Suggestion: Sensor Node

### ISSUE THREAD

**Issue by marcus-j-davies** [Anamico/node-red-contrib-alarm#28]
Hello,

Not been using this long, and so far, I really don't understand some things.

1) Trigger (Sensor Node)
    Seems to  completely ignore what I set, `Any Message` / `msg.payload.open == true`,
    I have passed this a payload of `msg.payload.open = false` and it triggers?
    Looking at the source code, `triggerType` does not seem to be utilised anywhere (at least from my investigation)?
    
    This is causing many false alarms 
    
2) Modes (Sensor Node)
    This tripped me up somewhat  -  I think this should be made more clear, as to what its intention is,
    Something like `Armed In Modes`. 
    
    Admittedly, I perceived this as the states that alarm system supports (as opposed to what states the Sensor is Armed under) 
    
    Lastly, any idea why `Off` is an option in what I call `Armed In Modes`?
    is it normal practice to arm a sensor when that alarm system is Off?
    
    Just seems odd.

**Comment by macinspak** [comment]
Oh, definitely maintained, just not at that pace right now. Should leave the ticket open for someone to pick up.

**Comment by macinspak** [comment]
OK, Part 1 I think is best handled with a generic fix we are working on with #25 and I've moved part 2 to a new ticket #29
