### ISSUE TITLE
Add a warning mode? Does that exist in HomeKit? Like entry an entry delay?

### ISSUE THREAD

**Issue by macinspak** [Anamico/node-red-contrib-alarm#3]
Or maybe allow the "State Changed" nodes to have an emit delay?

It could be faked by immediately sending the alarm to Homekit so you get it on your phone, but delay the same message to your monitoring or other automation or a home siren?

**Comment by rihani** [comment]
the around this is to set a delay, play a warning sound prior to delay expiry and then after delay is elapse, alarm is then set

**Comment by macinspak** [comment]
Thanks for that, it's certainly one way we can go. What I guess I was hoping is that homekit has a "warning" state, but maybe that doesn't exist any more? There used to be entry and exit delays, and they came in handy, especially if you forgot to disarm and walked in, you had time to disarm before the full siren went off as you heard the warning "beeps" or "pips" and it reminded you.

So we COULD do a similar thing with maybe a timer (configurable) and a different output or different node to use for warnings? But that won't alert anyone with homekit as there is no "warning" alarm state, only a "alarm" and "no alarm" state.

I guess it could still be helpful to not go full alarm on detection, what do you think? How would people use that warning node?

**Comment by crxporter** [comment]
To me, entry disarm warning would be like you suggested, "alarm" state for homekit but no siren in the house (yet)

exit delay would just be a delay between setting away from homekit and actually being armed away mode. Homekit would show "arming..."

**Comment by macinspak** [comment]
The delay on alarm nodes already facilitates this actually, see the updated [README.md](https://github.com/Anamico/node-red-contrib-alarm)
