### ISSUE TITLE
Alarm sensor does not update efter trigger and set off

### ISSUE THREAD

**Issue by dezral** [Anamico/node-red-contrib-alarm#6]
When the alarm have been triggered, and one have set the alarm off again it still says ALARM on the the Alarm sensor..

**Comment by macinspak** [comment]
awesome, thanks for picking that up, I'll have a look at it shortly. It's probably just not sending the state update to the node on reset.

**Comment by macinspak** [comment]
Fixing, will be released shortly in version 1.0.0
