### ISSUE TITLE
Value 0 not working in Format value mode

### ISSUE THREAD

**Issue by chri4chri** [Anamico/node-red-contrib-alarm#8]
If in value Mode, Home state 0 can‘t be injected

**Comment by macinspak** [comment]
Thanks for that, I can see the issue. Have patched it and will test and publish in the a few hours. It will be published in v1.1.1

**Comment by macinspak** [comment]
OK, just published the update 1.1.1, when it is visible on node-red please upgrade to 1.1.1, test and let me know if that fixes your problem.

**Comment by chri4chri** [comment]
I have just updated, and now the nodes have gone...
NodeRed did not find it anymore

**Comment by chri4chri** [comment]
found the issue - in node_modules under node-red-contrib-alarm there is the folder Alarm
I just renamed to alarm and it works - value 0 is also working lika a charm :-)
thanks

**Comment by macinspak** [comment]
Wow, that's weird. It's showing as "alarm" in lowercase in the repo but the distro appears as "Alarm"!
I've forced the folder update and have re-published, please check 1.1.2

**Comment by chri4chri** [comment]
Hi, 1.1.2 is working fine.
Many thanks!

**Comment by macinspak** [comment]
Thanks to YOU for reporting it. Many people for some reason just give up and don't bother reporting things. It's people like you that help the OpenSource community. We are not able to fix issues if we don't know about them!
