### ISSUE TITLE
No Alarm trigger in default Mode after modechange

### ISSUE THREAD

**Issue by chri4chri** [Anamico/node-red-contrib-alarm#9]
Hi, today I was playing around with „default“ mode. After starting NodeRed in homemode the first alarm was working. After switching to another state the alarm trigger won‘t trigger an alarm anymore.
I was sending the payload like  {"SecuritySystemTargetState": "1"} to the change state node.

**Comment by macinspak** [comment]
Do you have a “catch” node sending to a debug (whole message object) on the same flow? Try that and see if it’s throwing an exception

**Comment by chri4chri** [comment]
I have tried that, but there is no exception

**Comment by macinspak** [comment]
ok, strange, can you attach a screenshot and an export of your flow so I can understand your configuration and what could be going wrong.

**Comment by chri4chri** [comment]
Strange, it‘s now also working.
Thanks again!
